apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backuptool-k8s-agent.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backuptool-k8s-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  SERVER_URL: {{ required "server.url is required" .Values.server.url | quote }}
  AGENT_ID: {{ required "server.agentId is required" .Values.server.agentId | quote }}
  AGENT_TOKEN: {{ .Values.server.registrationToken | default "" | quote }}
